/**
 * pgvector 向量搜索功能测试
 *
 * 测试目标：
 * 1. 验证 pgvector 扩展已安装
 * 2. 验证 embedding 字段可以存储向量数据
 * 3. 验证余弦相似度搜索功能
 */

import { test, expect } from '@playwright/test';

test.describe('pgvector 向量搜索', () => {
  const API_BASE_URL = 'http://localhost:3000';

  test.beforeEach(async ({ request }) => {
    // 清理之前的测试数据
    await request.delete(`${API_BASE_URL}/api/admin/knowledge/documents/cleanup`);
  });

  test.describe('向量存储功能', () => {
    test('应该能够创建带有 embedding 的文档', async ({ request }) => {
      const response = await request.post(`${API_BASE_URL}/api/knowledge/documents`, {
        data: {
          title: '机器学习基础',
          content: '机器学习是人工智能的一个分支，使用统计方法让计算机学习。',
          category: 'technology',
          tags: ['AI', 'ML'],
          generate_embedding: true,
        },
      });

      expect(response.ok()).toBeTruthy();
      const doc = await response.json();
      expect(doc.id).toBeDefined();
      // Embedding is generated by AI Service, verify it exists
      if (doc.embedding) {
        expect(Array.isArray(doc.embedding) || typeof doc.embedding === 'object').toBeTruthy();
      }
    });

    test('应该能够批量创建文档并生成 embedding', async ({ request }) => {
      const response = await request.post(`${API_BASE_URL}/api/knowledge/documents/batch`, {
        data: {
          documents: [
            {
              title: '深度学习入门',
              content: '深度学习使用神经网络模拟人脑进行学习。',
              category: 'technology',
              tags: ['AI', 'Deep Learning'],
            },
            {
              title: '自然语言处理',
              content: '自然语言处理让计算机理解和生成人类语言。',
              category: 'technology',
              tags: ['AI', 'NLP'],
            },
          ],
          generate_embedding: true,
        },
      });

      expect(response.ok()).toBeTruthy();
      const docs = await response.json();
      expect(Array.isArray(docs)).toBeTruthy();
      expect(docs.length).toBe(2);
      docs.forEach((doc: any) => {
        expect(doc.embedding).toBeDefined();
      });
    });
  });

  test.describe('向量相似度搜索', () => {
    test.beforeEach(async ({ request }) => {
      // 创建测试文档
      await request.post(`${API_BASE_URL}/api/knowledge/documents/batch`, {
        data: {
          documents: [
            {
              title: '机器学习基础',
              content: '机器学习是人工智能的一个分支，使用统计方法让计算机学习。',
              category: 'technology',
              tags: ['AI', 'ML'],
            },
            {
              title: '深度学习入门',
              content: '深度学习使用神经网络模拟人脑进行学习。',
              category: 'technology',
              tags: ['AI', 'Deep Learning'],
            },
            {
              title: '烹饪技巧大全',
              content: '烹饪是一门艺术，需要掌握各种技巧和配料。',
              category: 'lifestyle',
              tags: ['cooking'],
            },
          ],
          generate_embedding: true,
        },
      });
    });

    test('应该使用向量相似度搜索返回最相关的结果', async ({ request }) => {
      const searchResponse = await request.post(`${API_BASE_URL}/api/knowledge/search`, {
        data: {
          query: '机器学习',
          limit: 10,
        },
      });

      expect(searchResponse.ok()).toBeTruthy();
      const results = await searchResponse.json();

      expect(Array.isArray(results.results)).toBeTruthy();
      expect(results.results.length).toBeGreaterThan(0);

      // 验证结果按相似度分数降序排列
      if (results.results.length > 1) {
        for (let i = 1; i < results.results.length; i++) {
          expect(results.results[i - 1].score).toBeGreaterThanOrEqual(results.results[i].score);
        }
      }

      // 验证第一个结果是最相关的
      expect(results.results[0].title).toContain('机器学习');
    });

    test('应该支持按 category 筛选', async ({ request }) => {
      const searchResponse = await request.post(`${API_BASE_URL}/api/knowledge/search`, {
        data: {
          query: '学习',
          category: 'technology',
          limit: 10,
        },
      });

      expect(searchResponse.ok()).toBeTruthy();
      const results = await searchResponse.json();

      // 验证所有结果都属于指定 category
      results.results.forEach((result: any) => {
        expect(result.category).toBe('technology');
      });
    });

    test('应该返回 embedding 信息（可选）', async ({ request }) => {
      const searchResponse = await request.post(`${API_BASE_URL}/api/knowledge/search`, {
        data: {
          query: '人工智能',
          limit: 5,
          include_embeddings: false,
        },
      });

      expect(searchResponse.ok()).toBeTruthy();
      const results = await searchResponse.json();

      // 验证返回结果结构
      expect(Array.isArray(results.results)).toBeTruthy();
      results.results.forEach((result: any) => {
        expect(result).toHaveProperty('id');
        expect(result).toHaveProperty('title');
        expect(result).toHaveProperty('content');
        expect(result).toHaveProperty('score');
      });
    });
  });

  test.describe('RAG 问答功能', () => {
    test.beforeEach(async ({ request }) => {
      // Create fresh test data for RAG tests
      await request.post(`${API_BASE_URL}/api/knowledge/documents/batch`, {
        data: {
          documents: [
            {
              title: '机器学习基础',
              content: '机器学习是人工智能的一个分支，使用统计方法让计算机学习。监督学习需要标记数据，无监督学习不需要标记数据。',
              category: 'technology',
              tags: ['AI', 'ML'],
            },
            {
              title: '深度学习入门',
              content: '深度学习使用神经网络模拟人脑进行学习。常见的神经网络包括卷积神经网络 (CNN) 和循环神经网络 (RNN)。',
              category: 'technology',
              tags: ['AI', 'Deep Learning'],
            },
          ],
          generate_embedding: true,
        },
      });
    });

    test('应该基于检索到的内容生成回答', async ({ request }) => {
      const response = await request.post(`${API_BASE_URL}/api/knowledge/query`, {
        data: {
          query: '什么是机器学习？',
          context_limit: 3,
        },
      });

      expect(response.ok()).toBeTruthy();
      const data = await response.json();

      expect(data).toHaveProperty('answer');
      expect(data).toHaveProperty('sources');
      // Sources may be empty if vector search doesn't find matches, which is acceptable
      expect(Array.isArray(data.sources)).toBeTruthy();
    });

    test('应该处理无匹配结果的情况', async ({ request }) => {
      const response = await request.post(`${API_BASE_URL}/api/knowledge/query`, {
        data: {
          query: 'xyzabc123 不存在的关键词',
          context_limit: 3,
        },
      });

      expect(response.ok()).toBeTruthy();
      const data = await response.json();

      expect(data).toHaveProperty('answer');
      // 无匹配时应返回友好提示
      expect(data.answer).toContain('抱歉') || expect(data.answer).toContain('没有找到');
    });
  });
});
